// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SkincareBookingService.Models;

public partial class Account
{
    public int AccountId { get; set; }

    public string AccountName { get; set; }

    public string Email { get; set; }

    public string Password { get; set; }

    public string PhoneNumber { get; set; }

    public DateTime? CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public int? RoleId { get; set; }

    public virtual Customer Customer { get; set; }

    public virtual Manager Manager { get; set; }

    public virtual Role Role { get; set; }

    public virtual SkinTherapist SkinTherapist { get; set; }

    public virtual Staff Staff { get; set; }
}