// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SkincareBookingService.Models;

public partial class Manager
{
    public int AccountId { get; set; }

    public string Name { get; set; }

    public virtual Account Account { get; set; }
}