// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SkincareBookingService.Models;

public partial class Manager
{
    public int ManagerId { get; set; }

    public string Name { get; set; }

    public string Email { get; set; }

    public string PhoneNumber { get; set; }

    public string Position { get; set; }

    public virtual ICollection<Report> Reports { get; set; } = new List<Report>();
}