// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SkincareBookingService.Models;

public partial class QuizAnswer
{
    public int AnswerId { get; set; }

    public int? CustomerId { get; set; }

    public int? QuestionId { get; set; }

    public string Answer { get; set; }

    public bool? IsCorrect { get; set; }

    public DateTime? CreatedAt { get; set; }

    public virtual Customer Customer { get; set; }

    public virtual QuizQuestion Question { get; set; }

    public virtual ICollection<QuizServiceResult> QuizServiceResults { get; set; } = new List<QuizServiceResult>();
}