// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SkincareBookingService.Models;

public partial class QuizQuestion
{
    public int QuestionId { get; set; }

    public int? QuestionSetId { get; set; }

    public string Content { get; set; }

    public string SkinTypeName { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public DateTime? CreatedAt { get; set; }

    public int? SkinTypeId { get; set; }

    public virtual QuizQuestionSet QuestionSet { get; set; }

    public virtual ICollection<QuizAnswer> QuizAnswers { get; set; } = new List<QuizAnswer>();

    public virtual SkinType SkinType { get; set; }
}