// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SkincareBookingService.Models;

public partial class QuizServiceResult
{
    public int QuizResultId { get; set; }

    public int? AnswerId { get; set; }

    public string Result { get; set; }

    public virtual QuizAnswer Answer { get; set; }

    public virtual ICollection<Service> Services { get; set; } = new List<Service>();
}