// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SkincareBookingService.Models;

public partial class Rating
{
    public int RatingId { get; set; }

    public int Stars { get; set; }

    public int ServiceId { get; set; }

    public int CustomerId { get; set; }

    public DateTime? CreatedAt { get; set; }

    public virtual Customer Customer { get; set; }
}