// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SkincareBookingService.Models;

public partial class Report
{
    public int ReportId { get; set; }

    public decimal TotalRevenue { get; set; }

    public int TotalAppointments { get; set; }

    public int TotalCustomers { get; set; }

    public string StaffFeedback { get; set; }
}