// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SkincareBookingService.Models;

public partial class Report
{
    public int ReportId { get; set; }

    public int? ManagerId { get; set; }

    public decimal? TotalRevenue { get; set; }

    public int? TotalAppointment { get; set; }

    public decimal? MonthlyRevenue { get; set; }

    public int? TotalFeedback { get; set; }

    public virtual Manager Manager { get; set; }
}