// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SkincareBookingService.Models;

public partial class Service
{
    public int ServiceId { get; set; }

    public string Name { get; set; }

    public string Description { get; set; }

    public decimal Price { get; set; }

    public int? ServiceTypeId { get; set; }

    public int? QuizResultId { get; set; }

    public DateTime? CreatedAt { get; set; }

    public virtual ICollection<Feedback> Feedbacks { get; set; } = new List<Feedback>();

    public virtual QuizServiceResult QuizResult { get; set; }

    public virtual ServiceType ServiceType { get; set; }

    public virtual ICollection<Slot> Slots { get; set; } = new List<Slot>();
}