// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SkincareBookingService.Models;

public partial class ServiceType
{
    public int ServiceTypeId { get; set; }

    public string Name { get; set; }

    public string Description { get; set; }

    public decimal? Price { get; set; }

    public string Period { get; set; }

    public string Genre { get; set; }

    public virtual ICollection<Service> Services { get; set; } = new List<Service>();
}