// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SkincareBookingService.Models;

public partial class ServiceType
{
    public int ServiceTypeId { get; set; }

    public string Name { get; set; }

    public string Description { get; set; }

    public decimal Price { get; set; }

    public int Period { get; set; }

    public int? ServiceId { get; set; }

    public virtual Service Service { get; set; }
}