// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SkincareBookingService.Models;

public partial class SkinTherapist
{
    public int SkinTherapistId { get; set; }

    public string Name { get; set; }

    public string Specialty { get; set; }

    public string Email { get; set; }

    public string Experience { get; set; }

    public virtual ICollection<Schedule> Schedules { get; set; } = new List<Schedule>();
}