// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SkincareBookingService.Models;

public partial class Slot
{
    public int SlotId { get; set; }

    public string Status { get; set; }

    public string Time { get; set; }

    public int? BookingId { get; set; }

    public int? ScheduleId { get; set; }

    public int? ServiceId { get; set; }

    public virtual Booking Booking { get; set; }

    public virtual Schedule Schedule { get; set; }

    public virtual Service Service { get; set; }
}